version: '3.1'

services:
  redis:
    image: redis:latest
    container_name: redis_local
    platform: linux/amd64  # Optional: specify platform if you encounter issues
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    platform: linux/amd64  # Optional: specify platform if you encounter issues
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  redis_data:
