name: App Management Workflow
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  path:
    - 'app-management/**'

jobs:
  run-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - uses: actions/cache@v2
    - run: npm ci
    - run: npm run test:cov
    

