name: App Management Workflow
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}
on:
  push:
    branches:
      - main
    # paths:
    #   - 'app-management/**'
  pull_request:
    branches:
      - main

# Set default wokring directory to app-management
defaults:
  run:
    working-directory: ./app-management

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: cp example.env .env
      - run: npm ci
      - run: npm run lint
      - run: npm run test:cov
      - run: npm run build
  docker_build:
    name: Github Container Registry build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./app-management
          file: ./app-management/Dockerfile
          push: true
          tags: ghcr.io/deployment-helper/app-management:lastest
  docker_build_aws:
    name: AWS Container Registry build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app-management
          file: ./app-management/Dockerfile
          push: true
          tags: 168490963129.dkr.ecr.us-east-1.amazonaws.com/app-management:latest
