name: Custom Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Custom message"
        required: true
        default: "Hello from API"
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Message: ${{ github.event.inputs.message }}"
          echo "Environment: ${{ github.event.inputs.environment }}"